#!/usr/bin/env bash

# Script name
SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")

# Script directory
SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") >/dev/null && pwd)

# Project directory
PROJECT_DIR=$(dirname "${SCRIPT_DIR}")

# Saved directory
SAVED_DIR=$(pwd)

# Architecture
case "$(uname -m)" in
    x86_64*)    ARCH=x64;;
    *)          ARCH=x86
esac

# Triplet
TRIPLET="linux-${ARCH}"

# Create build directories
mkdir -p "${PROJECT_DIR}/build/${TRIPLET}"

# Navigate to build directory
cd "${PROJECT_DIR}/build/${TRIPLET}"

# Generate CMake build system
cmake ../..

# Execute CMake build system
cmake --build .

# Restore directory
cd "${SAVED_DIR}"
